### PR TITLE
+) Added custom css class to default options

### PR DESCRIPTION
**Pull request by mariomurrent-softwaresolutions**
There should be an option to use custom css classes for each context menu, if you want so show more than one context menu with different container styling.

### CODE REVIEW

**Comment by mariomurrent-softwaresolutions** [comment]
Please also include a description how to use the makefile.

**Comment by jonataswalker** [comment]
Hey @mariomurrent-softwaresolutions I'd like to introduce (ASAP) a theme option and then you'll use your own.

For now you can override the CSS defaults with `!important`.

**Comment by jonataswalker** [comment]
Thanks for this Pull Request but that isn't the approach I'd like to use.

**Comment by mariomurrent-softwaresolutions** [comment]
Okay, maybe you can integrate it in the future ...

**Pull request closed without merging**
