### PR TITLE
Added updatePosition

### PR DESCRIPTION
**Pull request by Saurbaum**
To allow you to move the menu once all entries have been fetched from a remote source.

### CODE REVIEW

**Comment by Saurbaum** [comment]
Is there anything more you need me to change now I've backed out the update I did to the built output?

**Comment by jonataswalker** [comment]
Yes, @Saurbaum there are some inline comments.

**Comment by Saurbaum** [comment]
Apologies for that.  Still getting to grips with the GitHub interface.

**Comment by jonataswalker** [comment]
Thank you @Saurbaum. Merged.

**Pull request merged**
