### PR TITLE
Added open menu programmatically

### PR DESCRIPTION
**Pull request by AndersVittrup**
Build ok. I just added the option programmatically open the menu. I did not include the coordinates in openMenu.

I'm using this function in dev. on a project.

### CODE REVIEW

**Comment by jonataswalker** [comment]
Hey @AndersVittrup.

I was trying to avoid this method because there's a chance of some complications.

- You're not emitting `beforeopen` event;
- You're not computing `coordinates`;
- If you click outside (on the map) the menu there's no event registered to close it;

To say some. I'm not convinced but you (and others) can persuade me. Maybe a user-case?

**Comment by AndersVittrup** [comment]
Hi Jonatas,

I see your points. The reason to do this was to open the menu is for "long" click.
In my app i wanted to use this for tablet use. In browser on pc i use both this long click and right click. If i use click i just don't get the desired result.

Maybe it could be implemented in another way? - maybe you could give me some advice to implement it? - then i might give it a try :) - new pull request.

what do you think?

**Comment by jonataswalker** [comment]
So we need to provide mobile support. OpenLayers itself already has it, maybe we borrow from it.

I'll have to take the time to find the solution. Maybe you could do this search?

**Comment by AndersVittrup** [comment]
I did somre research. I found this official example:
http://openlayers.org/en/latest/examples/select-features.html

I looked at single click but it does not support the "press" function. So press and hold e.g. 300ms would be nice. I found this interaction:
https://github.com/Viglino/ol3-ext/blob/gh-pages/interaction/longtouchinteraction.js

Would you prefer to import this interaction (external) or create it here?
If you want it here I will help if you want me to :)

**Comment by jonataswalker** [comment]
@AndersVittrup Great! Let's shameless borrow from them and implement it here. May you please handle this in another PR?

Thank you. I really need some help.

**Comment by AndersVittrup** [comment]
Sound good. Can we maybe get in touch on mail? So the implementation of the interaction is done in a proper way?

**Pull request closed without merging**
